server.port: 8765
logging.level.org.springframework: info

spring:
  application:
    name: home-inventory-api-gateway
  cloud:
    config:
      enabled: false
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

