spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/macako/home-inventory.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}