server.port: 8888

spring:
  application:
    name: home-inventory-config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Desarrollo/git-localconfig-repo
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t