apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: home-inventory-user-service
  name: home-inventory-user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-inventory-user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: home-inventory-user-service
    spec:
      containers:
        - image: hectorolea/k8s-home-inventory-user-service:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: k8s-home-inventory-user-service
          envFrom:
            - configMapRef:
                name: home-inventory-user-service
          #env:
          #  - name: HOME_INVENTORY_ITEM_SERVICE_HOST
          #    value: http://home-inventory-item-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: home-inventory-user-service
  name: home-inventory-user-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: home-inventory-user-service
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  HOME_INVENTORY_ITEM_SERVICE_HOST: http://home-inventory-item-service
kind: ConfigMap
metadata:
  name: home-inventory-user-service
  namespace: default

