server.port: 8761

spring:
  application:
    name: home-inventory-naming-server
  cloud:
    config:
      enabled: false

eureka:
  client:
    instance:
      prefer-ip-address: true
    register-with-eureka: false
    fetch-registry: false