spring:
  application:
    name: home-inventory
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testDB
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: username
      password: password

logging.level.org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
