server.port: 8000
logging.level.org.springframework: debug

spring:
  application:
    name: home-inventory-item-service
  config:
    import: optional:configserver:http://root:s3cr3t@localhost:8888
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testDB
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: username
      password: password